version: '3.1'

services:
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: masta@gibdon.com
      PGADMIN_DEFAULT_PASSWORD: pregust0fth3w!nd
      PGADMIN_SERVER_JSON_FILE: /pgadmin4-config/servers.json
    ports:
      - 8088:80
    volumes:
      - ./pgadmin4-config/:/pgadmin4-config/

  # https://hub.docker.com/_/postgres/
  pgserver:
    image: postgres:12
    environment:
      POSTGRES_USER: masta
      POSTGRES_PASSWORD: pregust0fth3w!nd

    ports:
      - 5432:5432

    volumes:
      - /tmp/:/host-tmp/
